
<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">

		<label class="group-name" for="teem_show_content"><?php echo _t('ext.teem_videos.show_content'); ?></label>
		<div class="group-controls">
			<input type="checkbox" id="teem_show_content" name="teem_show_content" value="1" <?php if (FreshRSS_Context::$user_conf->teem_show_content != '') { echo 'checked'; }; ?>>
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>

<p>
	<?php echo _t('ext.teem_videos.updates'); ?>
	<a href="https://github.com/kevinpapst/freshrss-teem" target="_blank">GitHub</a>.
</p>
